[package]
name = "day_1"
version = "0.1.0"
edition = "2024"

[dev]
debug = true
opt-level = 0

[dependencies]
anyhow = "1.0.93"
regex = "1.11.1"
thiserror = "2.0.3"
aoc_utils = {path = "../../aoc_utils"}
