[package]
name = "day_20"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
aoc_utils = { version = "0.2024.0", path = "../../aoc_utils" }
pathfinding = "4.14.0"
thiserror = "2.0.11"
